# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='your_choice',
            new_name='choice_text',
        ),
    ]
